### ISSUE TITLE
Feat: 데이터베이스 설계

### ISSUE THREAD

**Issue by kduoh99** [moyeothon/momento_back#3]
## 🌿 이슈 요약

데이터베이스 전체 구조를 정의하고, 엔티티 간 연관관계를 매핑합니다.

## ✅ 체크 리스트

- [x] 기능 명세서에 부합하는 테이블 생성
- [x] 엔티티 간 연관관계 매핑

**Comment by shinyumin123** [comment]
혹시 각 테이블당 domain, repository, interface, service, dto, contollor는 각각 새로운 패키지를 만들어서 하시는 건가요? 아님 이미 있는 member, notification, team 패키지에 만드실 건가요?
![image](https://github.com/user-attachments/assets/f7bc7d89-60dd-4622-9307-5d2390ae49b6)

**Comment by kduoh99** [comment]
<img width="218" alt="스크린샷 2024-10-30 오후 3 16 16" src="https://github.com/user-attachments/assets/924fe54a-b740-430e-b9db-64116839b9d1">

전체적으로 이런 구조 생각하시면 됩니다!
